### ISSUE TITLE
Accept regular expressions in the list of consumer groups to monitor

### ISSUE THREAD

**Issue by devatherock** [devatherock/kafka-lag-monitor#4]
When accepting regular expressions, all consumer groups might need to be listed all the time and filtered to the ones whose names match the supplied regexes. Right now, all consumer groups get listed only when consumer group names are not supplied

**Comment by devatherock** [comment]
Should have all three configurations - exact consumer group name match, allowed groups regex and excluded groups regex, for maximum flexibility and ease. Also in that case, all consumer groups don't have to be listed if neither of the regexes are specified. Sample config with both allow list and deny list:

```yaml
kafka:
  lag-monitor:
    group-allowlist: "^deva.*-consumer$"
    group-denylist: ""^(console-consumer-|test-kafka-consumer-).*$"
```
